#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import sys
import re

downloadPATH = "/mnt/c/Users/thele/Downloads"

if len(sys.argv) == 1:
    print("Usage: copy [prefix] [-n]")
    exit(0)

NO_SPLIT = False
if "-n" in sys.argv:
    NO_SPLIT = True
    sys.argv.remove("-n")

prefix = sys.argv[1]
files = []
for file in os.listdir(downloadPATH):
    if not re.match(rf"{prefix}" + ".*", file):
        continue
    files.append(file)

for file in files:
    print(file)
print("*" * 20)
print(f"Matched {len(files)} files.")
print("*" * 20)

if len(files) == 0 or input("Confirm? [y/n] ").lower() != "y":
    exit(0)

print("*" * 20)
for oldName in files:
    newName = oldName
    if not NO_SPLIT:
        parts = oldName.rsplit(".", maxsplit=1)
        parts_name = parts[0].rsplit("_", maxsplit=1)
        if len(parts_name) >= 2:
            parts_name = parts_name[:-1]
        name = "_".join(parts_name)
        newName = name + ("." + parts[1] if len(parts) == 2 else "")
        print(f"{oldName} => {newName}")
        os.system(f"mv {downloadPATH}/{oldName} ./{newName}")
